import sys
import datetime
print("WELCOME TO THE LIBRARY SIMULATOR")
choice = input("which book do you want to read?? ")
lib_books =["THE ART OF PROGRAMMING",
"THE GREAT GATSBY",
"TO KILL A MOCKINGBIRD",
"HARRY POTTER AND THE SORCERER'S STONE",
"THE HITCHHIKER'S GUIDE TO THE GALAXY",
"PRIDE AND PREJUDICE",
"THE DA VINCI CODE",
"1984",
"THE CATCHER IN THE RYE",
"THE LORD OF THE RINGS",
"BRAVE NEW WORLD",
"THE HUNGER GAMES",
"THE ALCHEMIST",
"THE SHINING",
"WAR AND PEACE",
"THE HOBBIT",
"MOBY-DICK",
"CRIME AND PUNISHMENT",
"THE ODYSSEY",
"ALICE'S ADVENTURES IN WONDERLAND",
"THE CHRONICLES OF NARNIA: THE LION, THE WITCH AND THE WARDROBE",
"A TALE OF TWO CITIES",
"THE ROAD",
"THE GIRL WITH THE DRAGON TATTOO",
"THE HELP",
"THE PICTURE OF DORIAN GRAY",
"THE GRAPES OF WRATH",
"THE SCARLET LETTER",
"THE SECRET GARDEN",
"THE ADVENTURES OF SHERLOCK HOLMES",
"THE COUNT OF MONTE CRISTO",
"THE WIND IN THE WILLOWS",
"THE HANDMAID'S TALE",
"THE FAULT IN OUR STARS",
"THE STAND",
"THE SILENCE OF THE LAMBS",
"THE LITTLE PRINCE",
"THE METAMORPHOSIS",
"THE HOUND OF THE BASKERVILLES",
"THE WAR OF THE WORLDS"
]
issued_books=["THE CHRONICLES OF NARNIA: THE LION, THE WITCH AND THE WARDROBE",
"A TALE OF TWO CITIES",
"THE ROAD",
"THE GIRL WITH THE DRAGON TATTOO",
"THE HELP",
"THE PICTURE OF DORIAN GRAY",
"THE GRAPES OF WRATH",
"THE SCARLET LETTER",
"THE SECRET GARDEN",
"THE ADVENTURES OF SHERLOCK HOLMES",
"THE COUNT OF MONTE CRISTO",
"THE WIND IN THE WILLOWS",
"THE HANDMAID'S TALE",
"THE FAULT IN OUR STARS",
"THE STAND",
"THE SILENCE OF THE LAMBS",
"THE LITTLE PRINCE",
"THE METAMORPHOSIS",
"THE HOUND OF THE BASKERVILLES",
"THE WAR OF THE WORLDS"]
if choice.upper() in lib_books:
	print("The book "+choice+" is available")
	if choice.upper() in issued_books:
		print("But cuurently issued till",datetime.datetime.now().date())
		print("")
	else:
		print("The bokk is availabe in section ",lib_books.index("1984"))
		a = input("Do you want to issue this book? ")
		if a.upper() =='YES' or a.upper()=='NO':
			print("")

else:
	print("Sorry,the requested book is unavailable")
	print("")
print("THANK YOU FOR USING LIBRARY SIMULATOR")